# Authored by Matthew Samaha - Date: 2026-02-24
# Version 1.0

# Workflow to scan repository for hardcoded secrets
name: Secret Scan

# adding permissions
permissions:
  contents: read

on:
  # run on only important branches
  push:
    branches:
      - development
      - staging
      - main
  # Also run on PR to these branches
  pull_request:
    branches:
      - development
      - staging
      - main

jobs:
  gitleaks:
    # Github-hosted runner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Required to access repo files

      - name: Run Gitleaks Secret Scan
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --source . --verbose --redact # Scan entire repo